spring.application.name=E-Commerce-Backend

# =========================
# MySQL
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/ecommercedb
spring.datasource.username=root
spring.datasource.password=root

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Server
# =========================
server.port=${PORT:8081}

# =========================
# Groq / OpenAI Compatible
# =========================
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# =========================
# Ollama Embeddings
# =========================
spring.ai.model.chat=openai
spring.ai.model.embedding=ollama

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text

# =========================
# PGVector
# =========================
spring.ai.vectorstore.pgvector.database-name=ecommerce_ai
spring.ai.vectorstore.pgvector.schema-name=public

spring.autoconfigure.exclude=org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration

# =========================
# Logging
# =========================
debug=true
logging.level.org.springframework.security=DEBUG